### ISSUE TITLE
Unable to save data to MongoDB database

### ISSUE THREAD

**Issue by HalfMillennium** [jameshibbard/demo-node-app#2] opened 2019-12-30 20:15 UTC
For some reason, I haven't been able to save any data to my MongoDB data base. I first discovered this issue on my own version of your code, but then I cloned this exact repository and followed all of your installation instructions - the same deal.

I don't get any errors, and the .then() method executes and behaves as if registration was successful. Everything works properly _except_ the actual persisting of the data. I checked my user permissions on MongoDB's website, and it says that they're able to read/write to any database.

**Comment by jameshibbard** [comment] 2019-12-31 13:58
Hi,

Sorry to hear that you're having problems.

I just cloned and ran this repo to my system (Linux Mint 19.2, Mode 10.17.0, Mongo 3.6.3) and everything works as expected. This means a little more trouble shooting is required.

What is your OS / Node version / Mongo version?

Open a [Mongo shell](https://docs.mongodb.com/manual/mongo/) (by typing `mongo` from the command prompt) and enter:

```
use test
db.test.insert({ 'name': 'jim' })
db.getCollection('test').find()
```

What does that output?

**Comment by HalfMillennium** [comment] 2019-12-31 16:59
I'm on Windows 10, Node version 12.14.0 and Mongo version 4.2.2. The output of running those commands is: `{ "_id" : ObjectId("5e0b7e3246a7f704d56c067e"), "name" : "jim" }`

**Comment by jameshibbard** [comment] 2019-12-31 17:34
Ok, well you can obviously write to your MongoDB, so that's not the problem.
Can you post the contents of the `.env` file in your root directory (taking care to obscure any passwords).

**Comment by HalfMillennium** [comment] 2019-12-31 18:00
Sure:

**Comment by HalfMillennium** [comment] 2019-12-31 18:00
DATABASE=mongodb://localhost:27017/sp-node-article

**Comment by jameshibbard** [comment] 2020-01-01 10:02
Ok. I'll see if I can recreate your environment later on and test things out. In the meantime can you confirm the steps to reproduce your problem.

- You go to http://localhost:3000/
- You see a form asking for name and email
- You enter something valid and submit the form
- You see a "Thank you for your registration!" notice
- You go to http://localhost:3000/registrations
- No registrations are listed

Did I get that right?

**Comment by HalfMillennium** [comment] 2020-01-01 13:47
Yes, that's right.

**Comment by jameshibbard** [comment] 2020-01-01 16:29
Hi,

So I installed a copy of Win 10 on Virtual Box, installed Node v12.14.0 and Mongo v4.2.2. 

I then did the following:

1. Download the repo as a zip file and extracted it
2. Changed into the project root and ran `npm install`
3. Created a `.env` file in the project root
4. Added the following to the `.env` file: `DATABASE=mongodb://localhost:27017/node-demo-application`
5. Ran npm run watch
6. Visited http://localhost:3000 and created a new registration
7. Visited http://localhost:3000/registrations where I could view the successful registration

I'm afraid to say that the data was persisted as expected, meaning that it's something else with your setup which is causing the problem.

If I was you, I would try stripping out parts of the program until you can localize exactly where it is failing. When you have done this, feel free to head over to SitePoint forums and ask for help there. as described in the [Basic Setup](https://www.sitepoint.com/build-simple-beginner-app-node-bootstrap-mongodb/#basicsetup) section of the article.

For now, as I can't reproduce this error, I'm closing the issue.

Sorry I couldn't help more :(

**Closed as completed by jameshibbard** 2020-01-01 16:29 UTC

**Comment by HalfMillennium** [comment] 2020-01-01 19:48
Hm. Well, I'm incredibly grateful for your efforts, you've definitely set me on the right track.

**Comment by HalfMillennium** [comment] 2020-01-01 23:30
Actually, I made a mistake. The result of testing the database in command
line is actually "uncaught exception: ReferenceError: node is not defined".

**Comment by jameshibbard** [comment] 2020-01-02 07:24
Oh ok, so when you run:

```
use test
db.test.insert({ 'name': 'jim' })
db.getCollection('test').find()
```

The result is `uncaught exception: ReferenceError: node is not defined` and not `{ "_id" : ObjectId("5e0b7e3246a7f704d56c067e"), "name" : "jim" }` as previously stated.

Did I get that right?

**Comment by HalfMillennium** [comment] 2020-01-02 09:30
Yes, I didn't realize that I had slightly misspelled the name of my
database.

**Comment by HalfMillennium** [comment] 2020-01-02 09:35
Unless those commands were meant to be entered verbatim? When I run that
exactly, I get a successful response, but I'm assuming I'm meant to enter
my own database name in place of "test"?

**Comment by jameshibbard** [comment] 2020-01-02 09:36
Nope. Should work with `test`.

What were the commands you are running that gave you the `uncaught exception: ReferenceError: node is not defined` response?

**Comment by HalfMillennium** [comment] 2020-01-02 13:34
I typed in the name of my database

**Comment by jameshibbard** [comment] 2020-01-02 20:13
So, using `test` all is good, but using `sp-node-article` you get an error?

```
use test
db.test.insert({ 'name': 'jim' })
db.getCollection('test').find()

> { "_id" : ObjectId("5e0b7e3246a7f704d56c067e"), "name" : "jim" }
```

But:

```
use sp-node-article

> uncaught exception: ReferenceError: node is not defined
```

Did I get that right?

**Comment by HalfMillennium** [comment] 2020-01-02 21:48
Well, no, it lets me 'use' the database, but when I try to execute
'db.sp-node-article.insert(...)', I get that error.

**Comment by jameshibbard** [comment] 2020-01-03 07:03
Ah right, that's not an error so much as the mongo shell not accepting the name of the collection which contains a hyphen.

This should work:

```
use sp-node-article
db['sp-node-article'].insert({ 'name': 'jim' })
db.getCollection('sp-node-article').find()
```

Which unfortunately still doesn't explain why you cannot insert any data into the data base using the app.

**Comment by HalfMillennium** [comment] 2020-01-03 15:33
Oh, okay. Well, strangely, it says the insert into sp-node-article is
successful, but I get the same issue - nothing in the database. I even
retrieved the data, but still nothing shows up in Compass.

**Comment by jameshibbard** [comment] 2020-01-03 15:37
Man, that makes zero sense.
So you can insert and retrieve data from the mongo shell, but nothing is showing up in Compass?
I would almost be tempted to say that the issue is with Compass, but you said you are having the same problem with the app, which is independent of Compass.

**Comment by HalfMillennium** [comment] 2020-01-03 15:41
Exactly. This is all incredibly confusing.

**Comment by HalfMillennium** [comment] 2020-01-05 20:46
Alright, one last thing, as I understand that this issue might just be
beyond what you can assist me with.

But I've just tried it on my Mac, and I have mostly the same issue - except
localhost:3000/registrations DOES show all successful registrations, like
it should. Does this mean that the database I've been viewing on Compass
isn't the same one connected to the code?

**Comment by jameshibbard** [comment] 2020-01-06 08:43
> Does this mean that the database I've been viewing on Compass isn't the same one connected to the code?

I guess so. Which DB have you been viewing?

**Comment by HalfMillennium** [comment] 2020-01-06 14:33
Or maybe a different cluster? Because I check every database in my cluster
whenever I test the app.

**Comment by tganyan** [comment] 2020-03-10 17:42
A bit late and you probably already figured this out, but I had the exact same issue just now and finally figured out it was my own ignorance with compass. Just refreshing the collection doesn't seem to work, you also need to hit the little refresh button in the top left (where it lists how many dbs and how many collections you have total) to do a full refresh of the db list. After doing that once, I can refresh the collection and see new entries. Your issue might go deeper than that, but in case it derailed you and you gave up on it, figured I'd drop a comment. 

OS: Windows 10
